export class Constants {
    public static readonly i18nLabel = {
    jayWedsToral: 'jayWedsToral',
    omShreeGaneshayNamah: 'omShreeGaneshayNamah',
    mrDeepakAnd: 'mrDeepakAnd',
    mrsHeena: 'mrsHeena',
    requestYourGraciousPresence: 'requestYourGraciousPresence',
    jay: 'jay',
    with: 'with',
    toral: 'toral',
    daughterOfMrHarshad: 'daughterOfMrHarshad',
    mrsMamta: 'mrsMamta',
    meet: 'meet',
    the: 'the',
    brideAndGroom: 'brideAndGroom',
    toralIsCreative: 'toralIsCreative',
    aSimpleGirl: 'aSimpleGirl',
    chirpyHappyGoLucky: 'chirpyHappyGoLucky',
    withHerNature: 'withHerNature',
    jayIsCalm: 'jayIsCalm',
    talentedCoding: 'talentedCoding',
    deeplyFamilyOriented: 'deeplyFamilyOriented',
    handsomeCharmKindHeart: 'handsomeCharmKindHeart',
    aMessageFrom: 'aMessageFrom',
    beganWithTwoFamilies: 'beganWithTwoFamilies',
    withLoveBlessings: 'withLoveBlessings',
    withLove: 'withLove',
    jayAndToral: 'jayAndToral',
    lookingForward: 'lookingForward',
    onFriday: 'onFriday',
    venue: 'venue',
    damodarWadi: 'damodarWadi',
    ashokNagar: 'ashokNagar',
    timing: 'timing',
    timeOnwards: 'timeOnwards',
    clickForDirections: 'clickForDirections',
    thingsToKnow: 'thingsToKnow',
    toHelpYouAtEase: 'toHelpYouAtEase',
    hashtag: 'hashtag',
    whilePostingPhotos: 'whilePostingPhotos',
    hashtagValue: 'hashtagValue',
    ourFamiliesAreExcitedTo: 'ourFamiliesAreExcitedTo'
};
}